version: '3'

services:
  mamografia:
    container_name: mamografia
    build: 
      context: .
      dockerfile: Dockerfile
    image: python:last
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/opt
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  .:
  